ALTER TYPE "SomaShiftStatus" ADD VALUE 'TURNO_OTRA_PERSONA';
ALTER TYPE "SomaShiftStatus" ADD VALUE 'EXTERNO';
ALTER TYPE "SomaShiftStatus" ADD VALUE 'EXTERNO_NOCHE';

ALTER TABLE "Shift" ADD COLUMN "manualOverride" BOOLEAN NOT NULL DEFAULT false;